#:kivy 1.8
#:import kivy kivy

<BossScreen>:
	FloatLayout:
		DynImage:
			id: map
			source: "Images/Rooms/room_boss.png"
			pos: root.pos
			size: root.size
			keep_ratio: False
			allow_stretch: True

		DialogWidget:
			id: dialog
			size: (root.width, root.height * 0.2)
			icon: "Images/Characters/profil-test.png"

		RoomTitle:
			pos: (root.pos[0], root.size[1] - self.size[1])
			libelle: "Bureau du boss"