#:kivy 1.8
#:import kivy kivy

<LoadingScreen>:
	canvas:
        Color:
            rgba: 0.237, 0.220, 0.168, 1
        Rectangle:
            pos: root.pos
            size: root.size

	Label:
		pos: ((root.size[0] - size[0]) / 2, (root.size[1] - size[1]) / 2)
		text: "Chargement en cours"
		font_size: "50sp"

	Label:
		pos: ((root.size[0] - size[0]) / 2, root.size[1] / 3)
		text: "Veuillez patienter"
		font_size: "25sp"